### ISSUE TITLE
What is OTP

### ISSUE THREAD

**Issue by jcc5018** [hasan-ahani/filament-otp-input#2]
Hi, say your plugin in the filament plugins.  It would be more helpful if you define what OTP is, as not everyone knows what abbreviations are if they havent used it. Common practice is to Spell it out the first time using it, then provide the abbreviation.   (IE.. Automatic Teller machine --ATM) 

As of now, I think OTP is one time passcode?   Please consider that change in docs. Thanks

**Comment by hasan-ahani** [comment]
Hi there,

Thank you for your feedback and suggestion. We appreciate your input on improving our documentation. You're absolutely right, providing a full definition of "OTP" before using the abbreviation is a good practice to ensure clarity for all users. We'll make sure to update our documentation accordingly to spell out "One Time Passcode" on the first mention and provide the abbreviation in parentheses thereafter.

Thanks again for bringing this to our attention!

Best regards, Hassan
