### ISSUE TITLE
Problem installing with it, currently using Laravel 11 and Filament 3

### ISSUE THREAD

**Issue by vahnmarty** [hasan-ahani/filament-otp-input#4]
Problem 1
    - Root composer.json requires hasan-ahani/filament-otp-input * -> satisfiable by hasan-ahani/filament-otp-input[v1.0.0, ..., v1.0.5].
    - hasan-ahani/filament-otp-input[v1.0.0, ..., v1.0.5] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.3] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require hasan-ahani/filament-otp-input:*" to figure out if any version is installable, or "composer require hasan-ahani/filament-otp-input:^2.1" if you know which you need.

**Comment by hasan-ahani** [comment]
We now support Laravel 11.
