### ISSUE TITLE
No autocomplete on WKWebView

### ISSUE THREAD

**Issue by mischasigtermans** [hasan-ahani/filament-otp-input#5]
When working in WKWebView (iOS web app), the OTP autocomplete is not working. Looks like we need `autocomplete="one-time-password"` on the inputs.

**Comment by hasan-ahani** [comment]
Use the fix-autocomplete branch changes and let us know how it works.

**Comment by mischasigtermans** [comment]
Looks good, that's what I expected when I added `autocomplete('one-time-password')`.

**Comment by hasan-ahani** [comment]
Thank you for report @mischasigtermans

**Comment by mischasigtermans** [comment]
Autofocus is working properly on WKWebView now, but unfortunately it's not filling the inputs properly. Not sure why this functions differently than Safari. Any thoughts? Will investigate myself later.

https://github.com/hasan-ahani/filament-otp-input/assets/22501510/6d59121e-4502-4d60-a982-3f73c3b85e3e

**Comment by hasan-ahani** [comment]
You are attempting to enter text into a numeric field.
Which is not possible, even in the Chrome browser. Automatic number entry in the Chrome browser is managed by the browser itself. To resolve this issue, you can modify the view package file and use Alpine.js to address your problem.

**Comment by mischasigtermans** [comment]
Not sure if we're talking about the same issue here. I'm not using Chrome, but a native iOS WKWebView app. On Safari for iOS the autocomplete input is working as expected, but not for the app version (so with WKWebView). Any clue how this can be investigated?
