### ISSUE TITLE
Safari - last digit incorrect

### ISSUE THREAD

**Issue by aurawindsurfing** [hasan-ahani/filament-otp-input#7]
Hi @hasan-ahani thanks for the great package!

I noticed strange error.  While using autocomplete from messages the last digit completed in six fields is always incorrect.

I receive text:

<img width="251" alt="Screenshot 2024-05-25 at 08 32 52" src="https://github.com/hasan-ahani/filament-otp-input/assets/14302496/8105f2ac-e4c7-4e53-abb0-974a2029f0b5">

Then I use Safari to autocomplete and it completes last digit incorrectly:

<img width="600" alt="Screenshot 2024-05-25 at 08 33 03" src="https://github.com/hasan-ahani/filament-otp-input/assets/14302496/f0f14530-172f-4fdb-b21f-41ba801a241f">

Then ->afterStateUpdated dd()

<img width="295" alt="Screenshot 2024-05-25 at 08 33 20" src="https://github.com/hasan-ahani/filament-otp-input/assets/14302496/718b463a-8b41-4398-a9ff-61a59f676547">

Repeats for me 9 out of 10 tries.

I'm autocompleting on Safari on OSX and not on iOS

**Comment by hasan-ahani** [comment]
Hi! Thanks for bringing this up. Unfortunately, we don't have access to check this issue directly on Safari or OSX. However, you can override the view file and modify the Alpine.js code to better handle the autocomplete behavior. That should give you more control over how the input behaves in your specific setup.
